<?php declare(strict_types=1);

use SanderMuller\BoostCore\Config\BoostConfig;
use SanderMuller\BoostCore\Enums\Agent;
use SanderMuller\BoostCore\Enums\Tag;

/**
 * boost-core configuration.
 *
 * Generated by `vendor/bin/boost install`. Re-run that command to update
 * agents/vendors interactively, or hand-edit this file. After changes
 * run `vendor/bin/boost sync`.
 *
 * Docs: https://github.com/sandermuller/boost-core
 */
return BoostConfig::configure()->withTags([
    'boost-extension',
    'release-automation',
])->withDisabledEmitters([])
    // Which AI agents to publish skills/guidelines to. Add Agent enum cases.
    // Example: Agent::CLAUDE_CODE, Agent::CURSOR, Agent::COPILOT
    ->withAgents([
        Agent::CLAUDE_CODE,
    ])

    // Vendor packages allowed to publish skills/guidelines into your project.
    // Each entry is a Composer package name. Add via `vendor/bin/boost scan` or hand-edit.
    ->withAllowedVendors([
        'sandermuller/boost-core',
        'sandermuller/package-boost-laravel',
        'sandermuller/package-boost-php',
        'spatie/laravel-ray',
        'stolt/lean-package-validator',
    ])

    // Optionally disable specific FileEmitter implementations by FQCN.
    // ->withDisabledEmitters([SomeFqcn::class])

    // Skill tags: a vendor skill ships only when every tag in its
    // `metadata.boost-tags` is declared here. Unset = receive every
    // (untagged) skill. Accepts Tag enum cases or raw strings.
    // ->withTags([Tag::Php, Tag::Laravel])

    // Exclude specific vendor skills regardless of tags.
    // Each entry is a `vendor/package:skill-name` string.
    // ->withExcludedSkills(['acme/some-pack:unwanted-skill'])

    // Source paths default to the project root's .ai/skills and
    // .ai/guidelines. Override with an ABSOLUTE path only if your
    // sources live elsewhere. Avoid __DIR__-relative paths — they
    // break if this file moves (e.g. into .config/).
    // ->withSkillsPath('/absolute/path/to/skills')
    // ->withGuidelinesPath('/absolute/path/to/guidelines')
;
